<?php

namespace App\Console\Commands;

use App\City;
use App\Lake;
use App\Location;
use Illuminate\Console\Command;

class InsertLocations extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'location:insert';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $data = [
            "Zarasų rajonas" => [
                "Antalieptės marios",
                "Asavėlis",
                "Auslas",
                "Avilys",
                "Baltas",
                "Bebrinis",
                "Čičiris",
                "Duvenėlis",
                "Ėglis",
                "Griežta (Griežtų ežeras)",
                "Kumpuolis",
                "Kumpuoliukas",
                "Laukesas",
                "Ligajai",
                "Luodis",
                "Nečeskas",
                "Plavis",
                "Sartai",
                "Svaitutas",
                "Šventas",
                "Vasaknas",
                "Vencavas",
                "Zalvas",
                "Zalvys",
                "Zarasaitis",
                "Zarasas",
                "Žiegas"
              ],
              "Vilniaus rajonas" => [
                "Asveja",
                "Babrukas",
                "Bartuškio tvenkinys",
                "Dabinčius",
                "Elniakampis",
                "Ežeraitis",
                "Gaveikiai",
                "Giluitis",
                "Gilužis",
                "Ilgis",
                "Karvys",
                "Kernavė",
                "Malkėstas",
                "Mūšia",
                "Notiškis",
                "Pailgis",
                "Širvys",
                "Tapelių ežeras",
                "Tvenkinys Nemėžis",
                "Vievis",
                "Vilnoja",
                "Žalesas",
                "Žeimenis"
              ],
              "Vilnius" => [
                "Ežeraitis",
                "Gilužis",
                "Kernavė",
                "Lazdinių ežeras",
                "Meduvys",
                "Notiškis",
                "Tapelių ežeras",
                "Tvenkinys Nemėžis"
              ],
              "Trakų rajonas" => [
                "Akmenos",
                "Antakmenių ežeras",
                "Babrukas",
                "Baluosys",
                "Čiukiškių ežeras",
                "Dabinčius",
                "Drabužis",
                "Dubuklis",
                "Dvarčiai",
                "Galvė",
                "Gilušis",
                "Gilužis",
                "Guostas",
                "Ilgis",
                "Ilgutis",
                "Juodis",
                "Katyšiai",
                "Krakės",
                "Luka (Bernardinų ežeras)",
                "Margis",
                "Meduvys",
                "Monis",
                "Mošia",
                "Navas",
                "Nečiūnai",
                "Palaukinis",
                "Piktežeris",
                "Pilaitė",
                "Samanis",
                "Šamukas",
                "Šiemetys",
                "Sienius",
                "Skaistis",
                "Sprindžius",
                "Strėva",
                "Totoriškių",
                "Ungurys",
                "Vaisietis",
                "Viesai",
                "Vilkokšnis",
                "Vosyliukų malūno tvenkinys"
              ],
              "Trakai" => [
                "Akmenos",
                "Babrukas",
                "Baluosys",
                "Čiukiškių ežeras",
                "Dubuklis",
                "Dvarčiai",
                "Ešerinis",
                "Galvė",
                "Gilušis",
                "Gilužis",
                "Ilgis",
                "Ilgutis",
                "Luka (Bernardinų ežeras)",
                "Margis",
                "Mošia",
                "Navas",
                "Sienius",
                "Skaistis",
                "Totoriškių",
                "Ungurys",
                "Viesai",
                "Vilkokšnis"
              ],
              "Širvintų rajonas" => [
                "Bartuškio tvenkinys",
                "Karvys",
                "Kernavė",
                "Spėra",
                "Viesai"
              ],
              "Švenčionių rajonas" => [
                "Giluitis",
                "Kiaunas",
                "Kurtinėlis",
                "Pailgis",
                "Šaminis",
                "Sariai",
                "Šiekštys",
                "Snaigynas",
                "Sudota",
                "Sudotėlis",
                "Šventas",
                "Žeimenis"
              ],
              "Ukmergės rajonas" => [
                "Alaušai",
                "Bebrusai",
                "Ilgajis",
                "Kliepšių ežeras",
                "Kurėnai",
                "Labakaršis",
                "Roris",
                "Vepriai",
                "Žirnuojai"
              ],
              "Elektrėnai" => ["Asonas", "Elektrėnų marios", "Ilgis", "Vievis"],
              "Kauno rajonas" => ["Elektrėnų marios", "Kalviai", "Kauno marios"],
              "Kaunas" => ["Kauno marios"],
              "Prienų rajonas" => ["Guostas", "Lielius", "Veršiukas"],
              "Kaišiadorių rajonas" => ["Kalviai", "Kauno marios", "Strėva"],
              "Kėdainių rajonas" => ["Aristavos tvenkinys"],
              "Raseinių rajonas" => ["Kirkšnovės tvenkinys"],
              "Jonavos rajonas" => ["Tvenkinys Šveicarija"],
              "Rumšiškės" => ["Kauno marios"],
              "Klaipėdos rajonas" => [
                "Antalieptės marios",
                "Kalotė",
                "Kasučiai",
                "Kuršių marios",
                "Plateliai"
              ],
              "Klaipėda" => [
                "Antalieptės marios",
                "Kalotė",
                "Kasučiai",
                "Kuršių marios",
                "Malūno tvenkinys (Trinyčių ežeras)"
              ],
              "Šilutės rajonas" => ["Kuršių marios", "Vilkėno tvenkinys"],
              "Palanga" => ["Kunigiškiai"],
              "Šventoji" => ["Kasučiai", "Lazdininkų tvenkinys"],
              "Kretingos rajonas" => [
                "Juodupėnų tvenkinys",
                "Kasučiai",
                "Lazdininkų tvenkinys",
                "Plateliai"
              ],
              "Kretinga" => ["Akmena", "Armona", "Minija"],
              "Mingė (Minija)" => ["Minija"],
              "Druskininkai" => [
                "Alkos tvenkinys",
                "Ančia",
                "Aviris",
                "Bilsas",
                "Druskonis",
                "Dulgas",
                "Eglė",
                "Ešerinis",
                "Giedavardis",
                "Grūtas",
                "Ilgis",
                "Latežeris",
                "Liškiavis",
                "Roris",
                "Sagavas",
                "Šaulys",
                "Stirtos",
                "Trikojis",
                "Vidugašlis",
                "Vijūnėlis",
                "Vilkaitis",
                "Vilkinys"
              ],
              "Alytaus rajonas" => [
                "Alovė",
                "Atesys",
                "Daugai",
                "Didžiulis",
                "Dusia",
                "Gailintas",
                "Galvinis",
                "Giluitis",
                "Ilgis",
                "Lavysas",
                "Seirijis",
                "Stirtos",
                "Suvingis"
              ],
              "Alytus" => ["Daugai"],
              "Lazdijų rajonas" => [
                "Akmenių",
                "Ančia",
                "Aviris",
                "Babrai",
                "Dusia",
                "Gailiekas",
                "Galstas",
                "Giedavardis",
                "Ilgis",
                "Ilgutis",
                "Meteliai",
                "Neviedis",
                "Niedus",
                "Pastovys",
                "Sagavas",
                "Samanis",
                "Seirijis",
                "Seliovinis",
                "Šlavantas",
                "Šlavantėlis",
                "Snaigynas",
                "Trikojis",
                "Veisiejis",
                "Vidugašlis",
                "Vilkaitis",
                "Vilkinys",
                "Zapsys"
              ],
              "Varėnos rajonas" => [
                "Burokaraistis",
                "Ešerinis",
                "Glūkas",
                "Ilgis",
                "Lavysas",
                "Liškiavis"
              ],
              "Šiaulių rajonas" => [
                "Dulgas",
                "Geluva",
                "Gudeliai",
                "Paežerių ežeras",
                "Pašvinys"
              ],
              "Šiauliai" => ["Geluva"],
              "Kelmės rajonas" => [
                "Bridvaišis",
                "Dulgas",
                "Gilius",
                "Kibikštukas",
                "Lukštas"
              ],
              "Akmenės rajonas" => ["Sablauskių tvekinys"],
              "Radviliškio rajonas" => ["Gomerta", "Gudeliai"],
              "Joniškio rajonas" => ["Žvelgaičių ežeras"],
              "Marijampolė" => ["Armona", "Liolinga", "Šešupė", "Sūduonia"],
              "Vilkaviškio rajonas" => ["Paežerių ežeras", "Vištytis"],
              "Šakiai" => ["Siesartis"],
              "Šakių rajonas" => ["Bižinis"],
              "Kalvarija" => ["Aisetas", "Bebrinis", "Jurgežerių užtvanka"],
              "Panevėžio rajonas" => ["Labakaršis"],
              "Kupiškio rajonas" => ["Puožas"],
              "Rokiškio rajonas" => [
                "Bedugnis",
                "Dėlinis",
                "Dviragis",
                "Jūžintas",
                "Liūnas",
                "Petroškis",
                "Sartai",
                "Uostintas"
              ],
              "Pasvalio rajonas" => ["Pajiešmenių tvenkinys"],
              "Biržų rajonas" => ["Ageniškio tvenkinys", "Kilučiai"],
              "Plungės rajonas" => [
                "Beržoras",
                "Iešnalis",
                "Ilgis",
                "Maudutis",
                "Plateliai",
                "Sultekio tvenkinys",
                "Žiedelis"
              ],
              "Mažeikių rajonas" => ["Plateliai", "Plinkšiai"],
              "Telšių rajonas" => ["Gaudiešius", "Lūkstas"],
              "Telšiai" => ["Mastis"],
              "Rietavo rajonas" => ["Lūkstas"],
              "Šilalės rajonas" => ["Lūkstas", "Žvernas"],
              "Molėtų rajonas" => [
                "Aisetas",
                "Alaušai",
                "Alksnas",
                "Antalieptės marios",
                "Arinas",
                "Asveja",
                "Baltieji Lakajai",
                "Baluošas",
                "Bebrusai",
                "Duobis",
                "Dūriai",
                "Dvilypis",
                "Galuonai",
                "Gėliai",
                "Gėluotas",
                "Gilužis",
                "Grabuostas",
                "Gruodis",
                "Ilgis",
                "Ilgynas",
                "Kiementas",
                "Kirneilis",
                "Krasnolis",
                "Liminas",
                "Lukštas",
                "Luokesai",
                "Malkėstas",
                "Pastovys",
                "Salotis",
                "Siesartis",
                "Šlavinas",
                "Spalis",
                "Stirna",
                "Stirniai",
                "Virintai",
                "Želvos"
              ],
              "Anykščių rajonas" => [
                "Alaušas",
                "Juostinas",
                "Jurgiškiai",
                "Karališkių ežeras",
                "Keršis",
                "Kunigiškiai",
                "Nevėža",
                "Rubikiai"
              ],
              "Ignalinos rajonas" => [
                "Alksnaitis",
                "Alksnas",
                "Almajas",
                "Asalnikštis",
                "Ažvintis",
                "Baltis",
                "Baluošas",
                "Bedugnis",
                "Dringis",
                "Gulbinas",
                "Ilgis",
                "Kiaunas",
                "Labakaršis",
                "Liminas",
                "Luodis",
                "Lūšiai",
                "Lušykštis",
                "Pakalas",
                "Pakasas",
                "Palaukinis",
                "Palūšė",
                "Prūtas",
                "Šakarvai",
                "Šiekštys",
                "Srovinaitis",
                "Sungardai",
                "Tauragnas",
                "Tuolas",
                "Ūkojas",
                "Ūsiai",
                "Vėlis",
                "Virėkšta",
                "Žeimenis",
                "Žiezdras",
                "Ziezdris",
                "Žiežulinis",
                "Žilmas"
              ],
              "Ignalina" => [
                "Baltis",
                "Labakaršis",
                "Palaukinis",
                "Paplavinis",
                "Šiekštys",
                "Šiekštys",
                "Žeimenis",
                "Žiežulinis"
              ],
              "Utenos rajonas" => [
                "Aisetas",
                "Alaušai",
                "Alaušas",
                "Alksnas",
                "Biliakiemio tvenkinys",
                "Dusynas",
                "Giedrys",
                "Ilgis",
                "Kernadėtas",
                "Klykis",
                "Labelis",
                "Pakasas",
                "Paštys",
                "Tauragnas",
                "Utenos užtvanka",
                "Vaikesas",
                "Žiegas"
              ],
              "Zarasai" => [
                "Baltas",
                "Baltis",
                "Bebrinis",
                "Griežta (Griežtų ežeras)",
                "Laukesas",
                "Zarasaitis",
                "Zarasas"
              ],
              "Daugpilio rajonas" => ["Sila (Latvija)"],

              "Liepojos rajonas" => ["Liepoja (Latvija)", "Papė (Latvija)"],
              "Papė" => ["Papė (Latvija)"],
              "Ventspilio rajonas" => ["Pailgis", "Usma, Latvija"],

              "Seinų apskritis (Lenkija)" => [
                "Agurkių ežeras (Ogórki), Lenkija",
                "Antalieptės marios",
                "Balandis (Bałędź), Lenkija",
                "Baltis (Białe Augustowskie), Lenkija",
                "Bialė (Białe), Lenkija",
                "Bokšių ežeras (Boksze), Lenkija",
                "Dmitrowo, Lenkija",
                "Galadusys (Gaładuś), Lenkija",
                "Girėtas (Gieret), Lenkija",
                "Gluchių (Głuche), Lenkija",
                "Grimzdas (Gremzdy), Lenkija",
                "Ilgiai (Długie), Lenkija",
                "Judialis, Lenkija",
                "Jurkowo, Lenkija",
                "Maris (Pomorze), Lenkija",
                "Okuniewo, Lenkija",
                "Punia, Lenkija",
                "Seinai (Sejny), Lenkija",
                "Seivis (Sejwy), Lenkija",
                "Wierśnie, Lenkija",
                "Zelva (Zelwa), Lenkija"
              ],
              "Augustavo apskritis, Palenkės vaivadija" => [
                "Antalieptės marios",
                "Baltis (Białe Augustowskie), Lenkija",
                "Blizna (Blizno), Lenkija",
                "Garstyčia (Gorczyckie), Lenkija",
                "Kalinas (Kolno), Lenkija",
                "Mėta (Necko), Lenkija",
                "Orle, Lenkija",
                "Panievas (Paniewo), Lenkija",
                "Płaskie, Lenkija",
                "Sainas (Sajno), lenkija",
                "Sirvas (Serwy), Lenkija",
                "Studzieničnė (Studzieniczne), Lenkija",
                "Tobolovas (Tobołowo), Lenkija",
                "Vygriai (Wigry), Lenkija"
              ],
              "Suvalkų apskritis (Lenkija)" => [
                "Akmens ežeras (Okmin), Lenkija",
                "Ančia (Hańcza), Lenkija",
                "Antalieptės marios",
                "Arkadia, Lenkija",
                "Bolesty, Lenkija",
                "Didysis Šelmentas (Szelment Wielki), Lenkija",
                "Dovcenas (Dowcień), Lenkija",
                "Galadusys (Gaładuś), Lenkija",
                "Grimzdas (Gremzdy), Lenkija",
                "Ilgajis",
                "Ilgelis (Iłgielk), Lenkija",
                "Ilgiai (Długie), Lenkija",
                "Jačna (Jaczno), Lenkija",
                "Jalovas (Jałowo), Lenkija",
                "Kamendulas (Kamenduł), Lenkija",
                "Karšis (Leszczewek), Lenkija",
                "Kreivasis (Krzywe), Lenkija",
                "Kreivelis (Krejwelek), Lenkija",
                "Mauda, Lenkija",
                "Mažasis Šelmentas (Szelment Mały), Lenkija",
                "Okminek, Lenkija",
                "Okronglis / Apvalusis (Okrągłe), Lenkija",
                "Oževas (Ożewo), Lenkija",
                "Pertas (Perty), Lenkija",
                "Pietry, Lenkija",
                "Pobondziai (Pobondzie), Lenkija",
                "Potop, Lenkija",
                "Pšechodnie (Przechodnie), Lenkija",
                "Šiurpilis (Szurpiły), Lenkija",
                "Staw, Lenkija",
                "Sudawskie, lenkija",
                "Sumowo (Bakałarzewskie), Lenkija",
                "Sumowo (Ścibowo), Lenkija",
                "Vižainis (Wiżajny), Lenkija",
                "Vygriai (Wigry), Lenkija",
                "Wistuń, Lenkija"
              ],
              "Grajevo apskritis, Palenkės vaivadija" => ["Drenstvas (Dręstwo), Lenkija"],
              "Vilniaus apskritis" => [],
              "Utenos apskritis" => [],
              "Šiaulių apskritis" => [],
              "Kauno apskritis" => [],
              "Panevėžio apskritis" => [],
              "Birštonas" => [],
              "Šalčininkų rajonas" => [],
              "Skuodo rajonas" => [],
              "Šilutė" => [],
              "Wolsztyn apskritis, Didžiosios Lenkijos vaivadija" => [],
              "Mrongovo apskritis, Varmijos Mozūrų vaivadija" => [],
              "Jūrmala" => [],
              "Kekavas rajonas" => [],
              "Kuldīgas rajonas" => [],
              "Saulkrastų rajone" => [],
              "Bruocėnų savivaldybė" => [],
              "Jurbarko rajonas" => [],
              "Raudonė" => [],
              "Pagėgių rajonas" => [],
              "Tauragės rajonas" => [],
              "Pakruojo rajonas" => [],
              "Kazlų rūda" => [],
              "Panevėžys" => []
        ];

        foreach ($data as $location => $lakes) {
            $location_id = Location::where('name', $location)->first();
            if ($location_id) {
                echo "--> Found " . $location . PHP_EOL;
                foreach ($lakes as $lake_name) {
                    $lc = Lake::where('name', $lake_name)->first();
                    if (!$lc) {
                        echo '   --> Need to insert [ Location Id : '
                             . $location_id->id .' => Lake Name '. $lake_name . ' ]' . PHP_EOL;
                    } else {
                        echo '   --> Already inserted [ Location Id : '
                             . $location_id->id .' => Lake Name '. $lake_name . ' ]' . PHP_EOL;
                    }
                }
            }
        }
    }
}
